#!/bin/bash
docker run --rm -ti\
   --name "tilix"\
  --net=host --env="DISPLAY"\
  --volume="$HOME/.Xauthority:/root/.Xauthority:rw"\
  -v "$(pwd)/persistent_storage":/home/student/persistent\
  -v /var/run/dbus:/var/run/dbus\
  pzawad/tilix dbus-run-session tilix --session=persistent/tilix.json

#docker run --rm -ti --name "ubuntugtk" --privileged\
#  --net=host --env="DISPLAY"\
#  --volume="$HOME/.Xauthority:/root/.Xauthority:rw"\
#  -v "$(pwd)/persistent":/home/gnuradio/persistent\
#  -v /var/run/dbus:/var/run/dbus\
#  --device /dev/bus/usb\
#  pzawad/gnuradio tilix

# docker run -rm -ti --net=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --rm pzawad/ubuntu-x11 firefox
# ls
# -v /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket\
