#!/bin/bash
docker run --rm -ti\
   --name "tilix"\
  --net=host --env="DISPLAY"\
  --volume="$HOME/.Xauthority:/root/.Xauthority:rw"\
  -v "$(pwd)/persistent_storage":/home/student/persistent\
  -v /var/run/dbus:/var/run/dbus\
  pzawad/tilix dbus-run-session tilix --session=persistent/tilix.json
